window.ZUITI_DEMO_MOCKS = [
  {
    id: "delay-work-1",
    scene: "work",
    style: "delay",
    rawInput: "这个方案我今天给不了，先别催了。",
    tone: { politeness: 82, formality: 70, distance: 68 },
    outputs: {
      wechat: "这个方案我还需要再核一下细节，今天先给你一个初步方向，完整版本我明天下午前补上。",
      email: "您好，当前方案还需进一步确认关键细节。为保证内容准确，我计划先同步初步方向，并于明天下午前补充完整版本。",
      spoken: "我这边还差一点确认，今天先跟你对个大方向，完整方案我明天下午前给你。",
    },
    tags: ["给出时间", "缓冲催促", "保留主动权"],
  },
  {
    id: "delay-student-1",
    scene: "student",
    style: "delay",
    rawInput: "老师这周作业我可能交不上。",
    tone: { politeness: 88, formality: 76, distance: 72 },
    outputs: {
      wechat: "老师您好，这周作业我还差最后一部分，想申请晚一点提交，明晚前我一定补齐。",
      email: "老师您好，当前作业还在收尾中。为保证内容完整，我想申请适度延后提交，并承诺于明晚前补齐。",
      spoken: "老师，我这周作业还差一点收尾，能不能让我晚一点交，我明晚前一定补上。",
    },
    tags: ["礼貌延期", "说明进度", "明确承诺"],
  },
  {
    id: "delay-social-1",
    scene: "social",
    style: "delay",
    rawInput: "周末聚会我现在不想马上答应。",
    tone: { politeness: 74, formality: 38, distance: 34 },
    outputs: {
      wechat: "这周我先看看安排，晚一点再和你确认，别到时候答应了又放你鸽子。",
      email: "这周末的安排我还在确认中，想晚一点再正式回复，以免过早答应后临时变动。",
      spoken: "我先看下这周安排，晚点再确定，免得我现在答应了最后又改。",
    },
    tags: ["自然缓冲", "不伤关系", "避免失约"],
  },
  {
    id: "delay-formal-1",
    scene: "formal",
    style: "delay",
    rawInput: "这份材料今天来不及盖章。",
    tone: { politeness: 86, formality: 84, distance: 80 },
    outputs: {
      wechat: "目前材料还在流程中，今天可能无法完成盖章，我会在明日上午第一时间补办并同步给您。",
      email: "您好，当前材料仍在内部流转中，今日可能无法完成盖章。待流程完成后，我会于明日上午第一时间补发给您。",
      spoken: "这份材料今天可能还走不完流程，我明天上午一处理好就马上给您。",
    },
    tags: ["正式说明", "避免硬拒", "交代下一步"],
  },
  {
    id: "refuse-work-1",
    scene: "work",
    style: "refuse",
    rawInput: "这个周末你帮我值一下班。",
    tone: { politeness: 78, formality: 64, distance: 58 },
    outputs: {
      wechat: "这周末我这边已经有安排了，可能没法帮你值班，你可以看看有没有其他同事方便协调。",
      email: "您好，本周末我已有既定安排，暂时无法承担代班请求。建议尽快与其他同事协调，以免影响排班。",
      spoken: "这周末我确实排不开，可能帮不了你值班，你看看能不能再找下别的同事。",
    },
    tags: ["柔和拒绝", "不拖泥带水", "给替代方向"],
  },
  {
    id: "refuse-student-1",
    scene: "student",
    style: "refuse",
    rawInput: "你把答案直接发我吧。",
    tone: { politeness: 70, formality: 42, distance: 36 },
    outputs: {
      wechat: "我不太方便直接发答案，但如果你卡在某一步，我可以陪你一起看思路。",
      email: "我不适合直接提供答案，如有具体卡点，我愿意协助梳理解题思路。",
      spoken: "答案我就不直接发你了，但你哪一步不会我可以陪你看。",
    },
    tags: ["守住原则", "不显说教", "提供帮助"],
  },
  {
    id: "refuse-social-1",
    scene: "social",
    style: "refuse",
    rawInput: "你帮我去和他解释一下吧。",
    tone: { politeness: 72, formality: 32, distance: 40 },
    outputs: {
      wechat: "这件事我不太适合代你去说，还是你自己表达会更准确，我可以帮你顺一下说法。",
      email: "这件事由我代为说明可能不够合适，建议仍由您本人沟通。如有需要，我可以协助整理表达方式。",
      spoken: "这事我不太适合替你去说，你自己讲会更准确，我可以先帮你理理怎么说。",
    },
    tags: ["不越位", "保留支持", "关系友好"],
  },
  {
    id: "refuse-formal-1",
    scene: "formal",
    style: "refuse",
    rawInput: "能不能先别走流程，直接通融一下。",
    tone: { politeness: 84, formality: 90, distance: 86 },
    outputs: {
      wechat: "这类事项需要按既定流程处理，我这边不便直接通融，还请您理解。",
      email: "您好，该事项需按既定流程办理，我方无法绕过现有规则直接处理，敬请理解。",
      spoken: "这个事情还是得按流程来，我这边确实没办法直接通融。",
    },
    tags: ["规则优先", "语气克制", "边界明确"],
  },
  {
    id: "boundary-work-1",
    scene: "work",
    style: "boundary",
    rawInput: "这个需求你顺手做一下吧。",
    tone: { politeness: 74, formality: 66, distance: 72 },
    outputs: {
      wechat: "这个需求目前不在我负责范围内，如果要推进，建议和对应负责人确认优先级后再安排。",
      email: "您好，该需求当前不属于我的负责范围。若需推进，建议先由对应负责人确认优先级与资源安排。",
      spoken: "这个现在不在我负责范围里，如果要做，最好先和对应负责人把优先级确认一下。",
    },
    tags: ["职责清晰", "减少甩锅", "可继续协作"],
  },
  {
    id: "boundary-social-1",
    scene: "social",
    style: "boundary",
    rawInput: "你既然会就顺便帮我弄完。",
    tone: { politeness: 68, formality: 28, distance: 42 },
    outputs: {
      wechat: "我可以告诉你怎么弄，但这部分我就不直接替你做完了。",
      email: "我可以提供方法说明，但不适合直接代为完成全部内容。",
      spoken: "我能跟你说怎么弄，但我就不直接替你做完了。",
    },
    tags: ["不被顺手占用", "轻量支持", "边界自然"],
  },
  {
    id: "boundary-formal-1",
    scene: "formal",
    style: "boundary",
    rawInput: "你们先帮我内部协调好，我就不管了。",
    tone: { politeness: 82, formality: 88, distance: 84 },
    outputs: {
      wechat: "当前事项仍需您作为申请方配合确认关键信息，我方可以协助推进，但无法完全替代您处理。",
      email: "您好，当前事项仍需由申请方确认并提交关键信息。我方可配合协调，但无法完全代替申请方完成相关责任。",
      spoken: "这个事情还是需要您这边配合确认关键信息，我们可以协助，但不能完全替代您处理。",
    },
    tags: ["责任归位", "正式清晰", "避免失控"],
  },
  {
    id: "followup-work-1",
    scene: "work",
    style: "followup",
    rawInput: "这个需求你怎么还没回我。",
    tone: { politeness: 80, formality: 68, distance: 64 },
    outputs: {
      wechat: "想跟你同步一下，这个需求目前还没收到回复，如果今天能确认下进度，我这边后续安排会更顺一些。",
      email: "您好，想跟进一下该需求的当前进展。若今天能够确认反馈时间，将有助于我这边安排后续工作。",
      spoken: "我想跟进一下这个需求的进度，如果今天能有个回复，我这边后面会更好安排。",
    },
    tags: ["礼貌催办", "不显攻击", "推进明确"],
  },
  {
    id: "followup-student-1",
    scene: "student",
    style: "followup",
    rawInput: "组会材料你们到底谁交。",
    tone: { politeness: 72, formality: 52, distance: 46 },
    outputs: {
      wechat: "想确认一下组会材料由谁提交，如果今天能定下来，我这边好尽快补齐对应内容。",
      email: "想确认一下本次组会材料的提交流程及负责人，以便我尽快完成对应部分。",
      spoken: "我想确认一下这次材料最后是谁交，今天能定下来我这边就好继续补内容。",
    },
    tags: ["推进协作", "不甩情绪", "目标清楚"],
  },
  {
    id: "followup-formal-1",
    scene: "formal",
    style: "followup",
    rawInput: "我上次提交的申请怎么还没消息。",
    tone: { politeness: 88, formality: 86, distance: 82 },
    outputs: {
      wechat: "您好，想跟进一下我上次提交的申请当前处理进度，如有需要补充的材料也请告知。",
      email: "您好，想咨询一下此前提交申请的当前处理进度。如仍需补充材料或信息，烦请一并说明。",
      spoken: "您好，我想跟进一下之前那份申请现在的进度，如果还需要补材料也麻烦您告诉我。",
    },
    tags: ["正式跟进", "保留礼貌", "方便对方回复"],
  },
  {
    id: "decode-work-1",
    scene: "work",
    style: "decode",
    rawInput: "领导说这个方案你再想想。",
    tone: { politeness: 76, formality: 72, distance: 74 },
    outputs: {
      wechat: "如果把这句话翻成更明确的意思，大概率是：目前方案还不够成熟，需要你再补逻辑和可执行性。",
      email: "若将该反馈转译为更明确的要求，可以理解为：现有方案尚未达到可推进标准，需要进一步补充逻辑依据与执行细节。",
      spoken: "更直接点理解，这句话多半是在说现在这个方案还不够成熟，得再补逻辑和落地细节。",
    },
    tags: ["翻译潜台词", "降低误判", "帮助行动"],
  },
  {
    id: "decode-social-1",
    scene: "social",
    style: "decode",
    rawInput: "他说有空再约。",
    tone: { politeness: 62, formality: 20, distance: 30 },
    outputs: {
      wechat: "翻成更直接的话，可能是他现在没有特别强的见面意愿，短期内不一定会主动推进。",
      email: "若将这类表述转译为更明确的意思，通常表示对方当前暂未准备明确推进线下见面安排。",
      spoken: "更直白一点，这种话很多时候就是现在没那么想约，短期内也未必会主动推进。",
    },
    tags: ["看懂话外音", "减少内耗", "更现实判断"],
  },
  {
    id: "decode-student-1",
    scene: "student",
    style: "decode",
    rawInput: "老师说这部分还可以再完善。",
    tone: { politeness: 78, formality: 70, distance: 66 },
    outputs: {
      wechat: "更明确地说，这通常不是简单夸奖，而是在提醒这部分目前还不够完整，最好继续修改。",
      email: "若将该反馈转译为更明确的要求，可以理解为：当前内容尚未达到最终标准，仍需继续补充和完善。",
      spoken: "更直白一点，这句话一般是在提醒你现在这部分还不够完整，最好继续改。",
    },
    tags: ["避免误读", "清楚要求", "利于改进"],
  },
  {
    id: "sarcasm-work-1",
    scene: "work",
    style: "sarcasm",
    rawInput: "你们这个速度真是太高效了。",
    tone: { politeness: 58, formality: 62, distance: 68 },
    outputs: {
      wechat: "这边进度比预期慢不少，我需要一个更明确的时间点，不然整体安排会被一起拖住。",
      email: "当前进度明显慢于预期。为避免影响整体安排，我需要一个更明确且可兑现的时间计划。",
      spoken: "现在这个进度确实比预期慢了，我需要一个更明确的时间点，不然整体都会被拖住。",
    },
    tags: ["保留态度", "不做人身攻击", "把重点拉回进度"],
  },
  {
    id: "sarcasm-social-1",
    scene: "social",
    style: "sarcasm",
    rawInput: "你可真会临时放鸽子。",
    tone: { politeness: 56, formality: 18, distance: 26 },
    outputs: {
      wechat: "你这次临时改动确实让我挺措手不及的，下次如果有变动能早点说，我会更好安排。",
      email: "这次临时变动给我带来了一些安排上的影响。若后续有类似调整，若能提前告知会更方便协调。",
      spoken: "你这次临时变动确实让我有点措手不及，下次要是会改，早点说我会更好安排。",
    },
    tags: ["有情绪但不翻脸", "指出影响", "留改进空间"],
  },
  {
    id: "sarcasm-student-1",
    scene: "student",
    style: "sarcasm",
    rawInput: "你抄作业还挺有选择性的。",
    tone: { politeness: 52, formality: 22, distance: 24 },
    outputs: {
      wechat: "你参考得挺精准，但下次还是自己做会更稳，不然真问到细节就很容易露出来。",
      email: "你这次参考得比较集中，但从学习效果看，还是建议独立完成，避免对细节缺乏掌握。",
      spoken: "你这次参考得挺精准的，不过下次还是自己做吧，不然细节一问就容易露出来。",
    },
    tags: ["带点反差", "不直接羞辱", "把话收住"],
  },
];
